# This is a config for E2B sandbox template.
# You can use template ID (5jzixp6tedytlb8718yc) or template name (lovable-nextjs-clone-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-nextjs-clone-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-nextjs-clone-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-nextjs-clone-test-2')

team_id = "dc133bb0-e5b1-47e5-8ef1-613eb57dc26c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-nextjs-clone-test-2"
template_id = "5jzixp6tedytlb8718yc"
